Questão 1

In [1]:
import numpy as np

arr_uns = np.ones(8, dtype=int)
arr_aleatorio = np.random.randint(0, 10, 8)
arr_soma = arr_uns + arr_aleatorio

print("Array de 1's:", arr_uns)
print("Array aleatório:", arr_aleatorio)
print("Array resultante:", arr_soma)
print("Soma dos elementos:", arr_soma.sum())

if arr_soma.sum() >= 40:
    remodelado = arr_soma.reshape(4, 2)
else:
    remodelado = arr_soma.reshape(2, 4)

print("Array remodelado:\n", remodelado)
print("Formato:", remodelado.shape)


Array de 1's: [1 1 1 1 1 1 1 1]
Array aleatório: [4 3 7 3 2 7 7 6]
Array resultante: [5 4 8 4 3 8 8 7]
Soma dos elementos: 47
Array remodelado:
 [[5 4]
 [8 4]
 [3 8]
 [8 7]]
Formato: (4, 2)


Questão 2

In [2]:
campo = np.zeros((2, 2), dtype=int)
linha_bomba = np.random.randint(0, 2)
coluna_bomba = np.random.randint(0, 2)
campo[linha_bomba, coluna_bomba] = 1

posicoes_seguras = []
perdeu = False

for jogada in range(3):
    l = int(input(f"Jogada {jogada + 1} - linha (0 ou 1): "))
    c = int(input(f"Jogada {jogada + 1} - coluna (0 ou 1): "))

    if campo[l, c] == 1:
        print("Game Over! :( Try Again!")
        perdeu = True
        break

    if (l, c) not in posicoes_seguras:
        posicoes_seguras.append((l, c))

if not perdeu and len(posicoes_seguras) == 3:
    print("Congratulations! You beat the game! :)")

print("Campo:\n", campo)


Jogada 1 - linha (0 ou 1): 1
Jogada 1 - coluna (0 ou 1): 0
Jogada 2 - linha (0 ou 1): 0
Jogada 2 - coluna (0 ou 1): 1
Jogada 3 - linha (0 ou 1): 1
Jogada 3 - coluna (0 ou 1): 1
Game Over! :( Try Again!
Campo:
 [[0 0]
 [0 1]]


Questão 3

In [3]:
matriz = np.random.randint(0, 100, (3, 5))
print("Matriz:\n", matriz)

linhas, colunas = matriz.shape
total = linhas * colunas

print("Linhas:", linhas)
print("Colunas:", colunas)
print("Linhas * Colunas:", total)

if total % 2 == 0:
    print("Poderia se tornar um vetor unidimensional com número PAR de elementos.")
else:
    print("Poderia se tornar um vetor unidimensional com número ÍMPAR de elementos.")


Matriz:
 [[81 35 17 86 96]
 [44 41 11 46 15]
 [93 14 74 47 28]]
Linhas: 3
Colunas: 5
Linhas * Colunas: 15
Poderia se tornar um vetor unidimensional com número ÍMPAR de elementos.


Questão 4

In [ ]:
np.random.seed(10)
matriz = np.random.randint(1, 51, (4, 4))
print("Matriz:\n", matriz)

# a)
media_linhas = matriz.mean(axis=1)
media_colunas = matriz.mean(axis=0)
print("Média de cada linha:", media_linhas)
print("Média de cada coluna:", media_colunas)

# b)
print("Maior média entre as linhas:", media_linhas.max())
print("Maior média entre as colunas:", media_colunas.max())

# c)
valores, contagens = np.unique(matriz, return_counts=True)
print("Quantidade de aparições de cada número:")
for v, q in zip(valores, contagens):
    print(f"  {v}: {q}")

print("Números que aparecem 2 vezes:", valores[contagens == 2])


Questão 5

In [ ]:
zeros = np.zeros((3, 3), dtype=int)
uns = np.ones((3, 3), dtype=int)

soma = zeros + uns
escalar = 7
resultado = soma * escalar

print("Matriz de zeros:\n", zeros)
print("Matriz de uns:\n", uns)
print("Soma elemento a elemento:\n", soma)
print(f"Resultado multiplicado pelo escalar {escalar}:\n", resultado)

vetor = resultado.reshape(9)
print("Array unidimensional de 9 elementos:", vetor)


Questão 6

In [ ]:
arr = np.arange(10, 31, 2)
print("Array:", arr)

print("Maior valor:", arr.max(), "- índice:", arr.argmax())
print("Menor valor:", arr.min(), "- índice:", arr.argmin())
print("Soma de todos os elementos:", arr.sum())


Questão 7

In [ ]:
np.random.seed(7)
arr1 = np.random.randint(1, 11, 5)
arr2 = np.random.randint(1, 11, 5)

print("Array 1:", arr1)
print("Array 2:", arr2)

arr3 = np.concatenate((arr1, arr2))
print("Array concatenado:", arr3)

matriz = arr3.reshape(2, 5)
print("Matriz 2x5:\n", matriz)
